public enum LanguageMap {
    public static func languageIdentifier(forExtension ext: String) -> String? {
        languages[ext.lowercased()]
    }

    static let languages: [String: String] = [
        "swift": "swift",
        "m": "objc",
        "mm": "objc",
        "h": "c",
        "c": "c",
        "cc": "cpp",
        "cpp": "cpp",
        "cxx": "cpp",
        "hpp": "cpp",
        "hh": "cpp",
        "js": "javascript",
        "jsx": "jsx",
        "mjs": "javascript",
        "cjs": "javascript",
        "ts": "typescript",
        "tsx": "tsx",
        "mts": "typescript",
        "cts": "typescript",
        "py": "python",
        "rb": "ruby",
        "go": "go",
        "rs": "rust",
        "java": "java",
        "kt": "kotlin",
        "kts": "kotlin",
        "cs": "csharp",
        "fs": "fsharp",
        "scala": "scala",
        "dart": "dart",
        "php": "php",
        "lua": "lua",
        "pl": "perl",
        "pm": "perl",
        "r": "r",
        "jl": "julia",
        "sh": "shell",
        "bash": "bash",
        "zsh": "zsh",
        "fish": "fish",
        "html": "html",
        "htm": "html",
        "css": "css",
        "scss": "scss",
        "sass": "sass",
        "less": "less",
        "json": "json",
        "jsonc": "jsonc",
        "yaml": "yaml",
        "yml": "yaml",
        "xml": "xml",
        "plist": "xml",
        "xib": "xml",
        "storyboard": "xml",
        "svg": "xml",
        "md": "markdown",
        "markdown": "markdown",
        "txt": "text",
        "text": "text",
        "sql": "sql",
        "toml": "toml",
        "ini": "ini",
        "cfg": "ini",
        "conf": "ini",
        "properties": "properties",
        "gradle": "gradle",
        "groovy": "groovy",
        "vb": "vb",
        "asm": "asm",
        "s": "asm",
        "vim": "vim",
        "dockerfile": "dockerfile",
        "makefile": "makefile",
        "cmake": "cmake",
        "graphql": "graphql",
        "gql": "graphql",
        "proto": "protobuf",
        "tf": "terraform",
        "env": "shell",
        "gitignore": "gitignore",
        "gitconfig": "gitconfig",
    ]
}
